"""empty message

Revision ID: 206f66803696
Revises: 
Create Date: 2020-08-01 11:57:35.857359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '206f66803696'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=False),
    sa.Column('urgent', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    # ### end Alembic commands ###
